add: Landing page #7
lugvitc/FOSSit24 pull request #8
Opened 2024-03-26 19:57 UTC by mradigen

Closes #7 

Todo:
- [ ] Timeline
- [ ] Footer

2024-03-27 10:20 UTC, KreativeThinker requested changes

2024-03-27 10:20 UTC, KreativeThinker commented on src/app.html
Remove unnecessary font link

2024-03-27 10:20 UTC, KreativeThinker commented on src/lib/components/Navbar.svelte
> +			<a href="{base}/">{$user}</a>
Make user primary

2024-03-27 10:20 UTC, KreativeThinker commented on src/lib/components/Navbar.svelte
> +			<a href="{base}/">Welcome</a>
Change to sign out / logout

2024-03-27 10:20 UTC, KreativeThinker commented on src/lib/components/Navbar.svelte
> +			<a href="{base}/">Welcome</a>
Make into a button

2024-03-27 10:20 UTC, KreativeThinker commented on src/lib/components/Navbar.svelte
> +			<a href="{base}/">{$user}</a>
Make into a button

2024-03-27 13:38 UTC, KreativeThinker requested changes

2024-03-27 13:38 UTC, KreativeThinker commented on src/app.css
Reduce font sizes.

2024-03-27 13:38 UTC, KreativeThinker commented on src/app.css
Replace FOSSit logo in navbar with lug logo

2024-03-28 10:23 UTC, mradigen commented
Ignore the deployment issues, the current deployment is viewable at https://mradigen.github.io/FOSSit24

2024-04-04 15:43 UTC, KreativeThinker requested changes
- [x] Make overflow-x hidden
- [ ] Text still not showing in the two cards

2024-04-06 07:24 UTC, KreativeThinker approved these changes
Resolved

2024-04-06 07:25 UTC, merged